### PR TITLE
Add siebar dots

### PR DESCRIPTION
**Pull request by AdamSarach**

### CODE REVIEW

**Comment by luktar** [comment]
Because the navigation bar is transparent it's hard to see icons with a new background image.
Besides navigation bar looks like it was disabled.
Could you please do the following things in order to complete this task?
* make a background below the navigation bar button icons
* (optional) make navigation bar more visible. It can be done like in this example: https://mui.com/components/toggle-button/#color. Material 5 has already been imported.

image

**Review by luktar — CHANGES_REQUESTED** [review]
Look at the comment.

**Comment by AdamSarach** [comment]
Fixed. Have a look

**Review by luktar — APPROVED** [review]
Super

**Comment by luktar** [comment]
Wygląda świetnie.
image

**Pull request merged**
